### ISSUE TITLE
Set output and status

### ISSUE THREAD

**Issue by sagyos** [sensu-extensions/sensu-extensions-snmp-trap#11]
Hey,

I didn't see any way to set the output for each trap, is it possible?
Is there any way of changing the status manually, or by the sevirity of the trap configured in the MIB file?

Thanks in advance,
Sagi

**Comment by portertech** [comment]
Hey @sagyos ,

The check result output is currently being set automatically, via a configured mapping:

https://github.com/sensu-extensions/sensu-extensions-snmp-trap/blob/master/lib/sensu/extensions/snmp-trap.rb#L9

There are also cases where check result attributes are being set automatically:

https://github.com/sensu-extensions/sensu-extensions-snmp-trap/blob/master/lib/sensu/extensions/snmp-trap.rb#L190

We continue to improve the OID/MIB mappings with feedback. Do you have an example of an OID that should influence the check result output and/or severity?

**Comment by portertech** [comment]
@sagyos as of 0.0.33, you can configure varbind -> result and result status mappings! https://github.com/sensu-extensions/sensu-extensions-snmp-trap#configuration

**Comment by yuvarajanlga** [comment]
Hi portertech,

I am struggling to get work  snmp trap with sensu enterprise. i can see the traps are coming in. But the problem is its not binding to the proper status. I am sure there is an issues with varbind mapping. Even i m not sure, how to do this due to lack of my understanding on your sensu docs.  Kindly help me out. Since its been so long.

FYI:- 

cat snmp_trap.json 
{
  "snmp_trap": {
    "bind": "0.0.0.0",
    "port": 1062,
    "community": "***",
    "mibs_dir": "/etc/sensu/mibs/",
    "handlers": ["email","hipchat","tcp_socket","slack"],
    "contacts": "network",
    "result_attributes": {
      "datacenter": "LGA-Network",
      "handle": false
    },
    "result_map":[
      ["ifIndex", "$1"],
      ["ifAdminStatus", "$2"],
      ["ifOperStatus", "$3"],
      ["ifName", "$4"],
      ["ifType", "$5"]
      ],
    "result_status_map": [
      [".1.3.6.1.4.1.9.9.276.0.1", 2],
      ["IF-MIB::linkUp", 0]
     ]
  }
}
